TrajectoryPlannerROS:
  max_vel_x: 0.94671
  min_vel_x: 0.0
  max_rotational_vel: 1.5708
  min_in_place_rotational_vel: 0.0
  escape_vel: -0.1

  acc_lim_theta: 0.3926
  acc_lim_x: 0.23668
  acc_lim_y: 0.23668

  holonomic_robot: false
  meter_scoring: true
