obstacle_range: 2.0
raytrace_range: 30.0
footprint: [[0.5190, 0], [0, 0.4150],[-0.5190, 0],[0, -0.4150]]

transform_tolerance: 0.5
update_frequency: 5.0
publish_frequency: 3.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_scanner, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
