robot_p_diff_drive_controller:
  type: 'diff_drive_controller/DiffDriveController'
  left_wheel: 'front_left_wheel'
  right_wheel: 'front_right_wheel'
  publish_rate: 10
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25
  base_frame_id: "base_link"

  # publishes tf between odom and base_link
  enable_odom_tf: true

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier    : 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.94671   # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.23668   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.5708   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.3926   # rad/s^2
  wheel_separation          : 0.3     # m
  wheel_radius              : 0.1025  # m
